services:
  mongo:
    image: mongo:latest
    container_name: gofra_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gofra_backend
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      DB_NAME: "gofra"
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      SERVER_PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongo_data: