services:
  mongo:
    image: mongo:latest
    container_name: gofra_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "S3cr3tP4ssw0rd"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gofra_backend
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://admin:S3cr3tP4ssw0rd@mongo:27017"
      DB_NAME: "gofra"
      MONGO_USER: "admin"
      MONGO_PASSWORD: "S3cr3tP4ssw0rd"
      SERVER_PORT: 8080
      GIN_MODE: debug
    ports:
      - "8080:8080"
    restart: on-failure:5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gofra_frontend
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=localhost
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  mongo_data: