// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/buy": {
            "post": {
                "description": "Переводит гофера покупателю и списывает средства.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Покупка листинга",
                "parameters": [
                    {
                        "description": "Листинг для покупки",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.buyReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings": {
            "post": {
                "description": "Создаёт листинг и нового гофера, привязанного к продавцу.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Создание листинга с гофером",
                "parameters": [
                    {
                        "description": "Описание листинга",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createListingReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.createListingResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}": {
            "get": {
                "description": "Возвращает листинг с данными гофера. Скрывает описание для посторонних пользователей.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Получение листинга",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.listingResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}/bump": {
            "post": {
                "description": "Списывает стоимость поднятия с баланса продавца (уязвим к uint underflow).",
                "tags": [
                    "listings"
                ],
                "summary": "Поднять листинг",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}/image": {
            "get": {
                "description": "Возвращает изображение листинга или редиректит на исходный URL.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Получение изображения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Изображение",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "302": {
                        "description": "Redirect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}/image/meta": {
            "get": {
                "description": "Возвращает сохранённые метаданные изображения листинга.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Метаданные изображения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.imageMetaResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}/image_from_url": {
            "post": {
                "description": "Загружает изображение для листинга по произвольному URL (уязвимо для SSRF).",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Загрузка изображения по URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "URL источника",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.fetchImageReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/listings/{id}/image_upload": {
            "post": {
                "description": "Принимает multipart-файл и сохраняет Base64 представление.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Загрузка файла изображения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID листинга",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл изображения",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Аутентифицирует пользователя и устанавливает cookie сессии.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.meResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/market": {
            "get": {
                "description": "Возвращает список карточек гоферов по фильтру. Уязвим для NoSQL-инъекций.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market"
                ],
                "summary": "Поиск карточек в маркетплейсе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MongoDB JSON фильтр",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество элементов на страницу",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поле сортировки (price_asc, price_desc)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.marketSearchResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "description": "Возвращает текущего авторизованного пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.meResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/my-gofers": {
            "get": {
                "description": "Возвращает гоферов, которыми владеет текущий пользователь.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Мои гоферы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.goferListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/my-listings": {
            "get": {
                "description": "Возвращает листинги текущего пользователя вместе с гоферами.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "listings"
                ],
                "summary": "Мои листинги",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.listingListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "Создаёт пользователя и авторизует его через cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.meResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.buyReq": {
            "type": "object",
            "required": [
                "listing_id"
            ],
            "properties": {
                "listing_id": {
                    "description": "Идентификатор листинга",
                    "type": "string"
                }
            }
        },
        "handlers.createListingReq": {
            "type": "object",
            "required": [
                "description",
                "gofer_name",
                "gofer_rarity",
                "price"
            ],
            "properties": {
                "description": {
                    "description": "Описание",
                    "type": "string"
                },
                "gofer_name": {
                    "description": "Имя гофера",
                    "type": "string"
                },
                "gofer_rarity": {
                    "description": "Редкость",
                    "type": "integer"
                },
                "price": {
                    "description": "Цена",
                    "type": "integer"
                }
            }
        },
        "handlers.createListingResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "handlers.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.fetchImageReq": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "description": "URL изображения",
                    "type": "string"
                }
            }
        },
        "handlers.goferItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rarity": {
                    "type": "integer"
                }
            }
        },
        "handlers.goferListResponse": {
            "type": "object",
            "properties": {
                "gofers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.goferItem"
                    }
                }
            }
        },
        "handlers.imageMetaResp": {
            "type": "object",
            "properties": {
                "content_type": {
                    "description": "Тип содержимого",
                    "type": "string"
                },
                "debug_snippet_b64": {
                    "description": "Сниппет для отладки",
                    "type": "string"
                },
                "fetched_at": {
                    "description": "Время загрузки",
                    "type": "string"
                }
            }
        },
        "handlers.listingGoferResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Идентификатор",
                    "type": "string"
                },
                "name": {
                    "description": "Имя",
                    "type": "string"
                },
                "rarity": {
                    "description": "Редкость",
                    "type": "integer"
                }
            }
        },
        "handlers.listingImageResp": {
            "type": "object",
            "properties": {
                "content_type": {
                    "description": "Тип содержимого",
                    "type": "string"
                },
                "debug_snippet_b64": {
                    "description": "Сниппет для отладки",
                    "type": "string"
                },
                "fetched_at": {
                    "description": "Время загрузки",
                    "type": "string"
                },
                "source_url": {
                    "description": "URL источника",
                    "type": "string"
                }
            }
        },
        "handlers.listingListResponse": {
            "type": "object",
            "properties": {
                "listings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.listingResp"
                    }
                }
            }
        },
        "handlers.listingResp": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "description": "Идентификатор покупателя",
                    "type": "string"
                },
                "created_at": {
                    "description": "Время создания",
                    "type": "string"
                },
                "description": {
                    "description": "Описание",
                    "type": "string"
                },
                "gofer": {
                    "description": "Гофер",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.listingGoferResp"
                        }
                    ]
                },
                "gofer_id": {
                    "description": "Идентификатор гофера",
                    "type": "string"
                },
                "id": {
                    "description": "Идентификатор листинга",
                    "type": "string"
                },
                "image": {
                    "description": "Изображение",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handlers.listingImageResp"
                        }
                    ]
                },
                "is_sold": {
                    "description": "Флаг продажи",
                    "type": "boolean"
                },
                "price": {
                    "description": "Цена",
                    "type": "integer"
                },
                "seller_id": {
                    "description": "Идентификатор продавца",
                    "type": "string"
                }
            }
        },
        "handlers.loginReq": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.marketGoferResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rarity": {
                    "type": "integer"
                }
            }
        },
        "handlers.marketImageResp": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "debug_snippet_b64": {
                    "type": "string"
                },
                "fetched_at": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                }
            }
        },
        "handlers.marketSearchResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.serviceCard"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.meResp": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "handlers.registerReq": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.serviceCard": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gofer": {
                    "$ref": "#/definitions/handlers.marketGoferResp"
                },
                "gofer_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "$ref": "#/definitions/handlers.marketImageResp"
                },
                "is_sold": {
                    "type": "boolean"
                },
                "price": {
                    "type": "integer"
                },
                "seller_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "sid",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Gofra Market API",
	Description:      "Attack-Defense CTF сервис магазина гоферов с преднамеренными уязвимостями (NoSQL injection, SSRF, uint underflow).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
